version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  module_system = "commonjs"
  dialect = "typescript"
  environment = ["nodejs", "vitest"]
  plugins = ["react"]

[[analyzers]]
name = "sql"
enabled = true
