FROM --platform=linux/amd64 node:24-bookworm-slim AS builder

WORKDIR /app

RUN npm install --global npm@11.19.1 --ignore-scripts

COPY package.json package-lock.json ./
COPY scripts/verify-dependency-lifecycle-scripts.cjs ./scripts/verify-dependency-lifecycle-scripts.cjs

RUN node scripts/verify-dependency-lifecycle-scripts.cjs \
  && npm ci --ignore-scripts \
  && npm rebuild esbuild unrs-resolver --ignore-scripts=false

COPY . .

ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_HONEYBADGER_API_KEY
ARG NEXT_PUBLIC_HONEYBADGER_ASSETS_URL
ARG ACADEMIA_ARCANA_REVISION

ENV NODE_ENV=production \
  PORT=10000 \
  HOSTNAME=0.0.0.0 \
  NEXT_PUBLIC_APP_ENV=production \
  NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL} \
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY} \
  NEXT_PUBLIC_HONEYBADGER_API_KEY=${NEXT_PUBLIC_HONEYBADGER_API_KEY} \
  NEXT_PUBLIC_HONEYBADGER_ASSETS_URL=${NEXT_PUBLIC_HONEYBADGER_ASSETS_URL} \
  NEXT_PUBLIC_HONEYBADGER_REVISION=${ACADEMIA_ARCANA_REVISION} \
  ACADEMIA_ARCANA_REVISION=${ACADEMIA_ARCANA_REVISION}

RUN npm run build \
  && npm prune --omit=dev --ignore-scripts \
  && mkdir -p .next/cache

FROM --platform=linux/amd64 node:24-bookworm-slim AS runtime

WORKDIR /app

ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_HONEYBADGER_API_KEY
ARG NEXT_PUBLIC_HONEYBADGER_ASSETS_URL
ARG ACADEMIA_ARCANA_REVISION

ENV NODE_ENV=production \
  PORT=10000 \
  HOSTNAME=0.0.0.0 \
  NEXT_PUBLIC_APP_ENV=production \
  NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL} \
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY} \
  NEXT_PUBLIC_HONEYBADGER_API_KEY=${NEXT_PUBLIC_HONEYBADGER_API_KEY} \
  NEXT_PUBLIC_HONEYBADGER_ASSETS_URL=${NEXT_PUBLIC_HONEYBADGER_ASSETS_URL} \
  NEXT_PUBLIC_HONEYBADGER_REVISION=${ACADEMIA_ARCANA_REVISION} \
  ACADEMIA_ARCANA_REVISION=${ACADEMIA_ARCANA_REVISION}

COPY --from=builder --chown=node:node /app /app

USER node

EXPOSE 10000

CMD ["node", "node_modules/next/dist/bin/next", "start"]
