import type { ThemeTokens } from "./types";

export const baseTokens: ThemeTokens = {
  surfaces: {
    canvas: "#17151C",
    panel: "#211D28",
    elevated: "#2A2432",
    floating: "#30283A",
    modal: "#352C41",
    inset: "#141219",
  },
  text: {
    primary: "#E6DFEC",
    secondary: "#C2B8C9",
    muted: "#A99DB0",
    inverse: "#211D28",
  },
  border: {
    default: "#9689A0",
    strong: "#A099A8",
  },
  accent: {
    primary: "#B9A4CF",
    secondary: "#8E79A6",
  },
  status: {
    success: "#86B89A",
    warning: "#D0B477",
    danger: "#CA888E",
    info: "#86A8C4",
  },
  focus: {
    ring: "#D7C6E6",
    width: "3px",
    offset: "3px",
  },
  radius: {
    sm: "0.375rem",
    md: "0.625rem",
    lg: "0.875rem",
    xl: "1.25rem",
    pill: "999px",
  },
  spacing: {
    xs: "0.25rem",
    sm: "0.5rem",
    md: "1rem",
    lg: "1.5rem",
    xl: "2rem",
    "2xl": "3rem",
    "3xl": "4rem",
  },
  sizing: {
    controlSm: "2.25rem",
    controlMd: "2.75rem",
    controlLg: "3.25rem",
    iconSm: "1rem",
    iconMd: "1.25rem",
    iconLg: "1.5rem",
    contentMax: "72rem",
    pageMax: "96rem",
  },
  typography: {
    body: ""Acumin Pro", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif",
    heading: ""Sanvito Pro", Georgia, serif",
    display: ""Sanvito Pro", Georgia, serif",
    label: ""Acumin Pro", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif",
    caption: ""Acumin Pro", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif",
    code: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
    numeric: ""Acumin Pro", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif",
  },
  typeScale: {
    xs: "0.75rem",
    sm: "0.875rem",
    md: "1rem",
    lg: "1.125rem",
    xl: "1.25rem",
    "2xl": "1.5rem",
    "3xl": "1.875rem",
    "4xl": "2.25rem",
    "5xl": "3.5rem",
  },
  lineHeight: {
    tight: "1.1",
    normal: "1.5",
    relaxed: "1.65",
  },
  shadows: {
    sm: "0 1px 2px rgb(0 0 0 / 0.24)",
    md: "0 8px 24px rgb(0 0 0 / 0.28)",
    lg: "0 14px 36px rgb(0 0 0 / 0.32)",
    floating: "0 18px 48px rgb(0 0 0 / 0.34)",
    modal: "0 24px 72px rgb(0 0 0 / 0.42)",
  },
  motion: {
    fast: "120ms",
    normal: "180ms",
    slow: "280ms",
    reduced: "0ms",
    easingStandard: "cubic-bezier(0.2, 0, 0, 1)",
    easingEmphasized: "cubic-bezier(0.2, 0.8, 0.2, 1)",
  },
  breakpoints: {
    sm: "40rem",
    md: "48rem",
    lg: "64rem",
    xl: "80rem",
  },
  zIndex: {
    base: "0",
    sticky: "20",
    dropdown: "30",
    modal: "40",
    toast: "50",
  },
  opacity: {
    muted: "0.72",
    disabled: "0.56",
    overlay: "0.72",
  },
  density: {
    compact: "0.875",
    comfortable: "1",
  },
  effects: {
    glow: "0 0 0 transparent",
    texture: "none",
  },
};
