/**
 * Exact plugin names supplied by the current ChatGPT plugin catalog export.
 *
 * This is a catalog, not a claim that each entry has a web API or MCP
 * endpoint available to the Academia Arcana application.
 */
export const CHATGPT_PLUGIN_CATALOG = [
  { name: "1 Billion Brain Cells", source: "chatgpt-catalog" as const },
  { name: "A-Z Daily Word", source: "chatgpt-catalog" as const },
  { name: "A-Z Dictionary", source: "chatgpt-catalog" as const },
  { name: "A-Z Holy Bible", source: "chatgpt-catalog" as const },
  { name: "Academic Writing Toolkit", source: "chatgpt-catalog" as const },
  { name: "Ace Knowledge Graph", source: "chatgpt-catalog" as const },
  { name: "Ace Quiz Maker", source: "chatgpt-catalog" as const },
  { name: "Agentic Course Redesign", source: "chatgpt-catalog" as const },
  { name: "AI4F Japanese Study", source: "chatgpt-catalog" as const },
  { name: "All Tide Times", source: "chatgpt-catalog" as const },
  { name: "All your Horoscopes", source: "chatgpt-catalog" as const },
  { name: "Amass", source: "chatgpt-catalog" as const },
  { name: "AnyLessonPlan for Teachers", source: "chatgpt-catalog" as const },
  { name: "Ask Tarot Cards", source: "chatgpt-catalog" as const },
  { name: "Assessment Generator", source: "chatgpt-catalog" as const },
  { name: "Astro Scope: Astrology", source: "chatgpt-catalog" as const },
  { name: "Astrologic", source: "chatgpt-catalog" as const },
  { name: "Background Music", source: "chatgpt-catalog" as const },
  { name: "Beast Academy - All Ten", source: "chatgpt-catalog" as const },
  { name: "Bee Spelling", source: "chatgpt-catalog" as const },
  { name: "Biohub ESM", source: "chatgpt-catalog" as const },
  { name: "Bodhaka Virtual Labs", source: "chatgpt-catalog" as const },
  { name: "Brisk Teaching", source: "chatgpt-catalog" as const },
  { name: "Canva", source: "chatgpt-catalog" as const },
  { name: "Caveman Mode", source: "chatgpt-catalog" as const },
  { name: "Chessvia Openings", source: "chatgpt-catalog" as const },
  { name: "Chessy", source: "chatgpt-catalog" as const },
  { name: "Chymia", source: "chatgpt-catalog" as const },
  { name: "Common Room", source: "chatgpt-catalog" as const },
  { name: "Consensus", source: "chatgpt-catalog" as const },
  { name: "Course Studio", source: "chatgpt-catalog" as const },
  { name: "Data", source: "chatgpt-catalog" as const },
  { name: "DataCamp", source: "chatgpt-catalog" as const },
  { name: "Digital Compass", source: "chatgpt-catalog" as const },
  { name: "Drill", source: "chatgpt-catalog" as const },
  { name: "Dropbox", source: "chatgpt-catalog" as const },
  { name: "EduInsights", source: "chatgpt-catalog" as const },
  { name: "Elicit", source: "chatgpt-catalog" as const },
  { name: "Emona", source: "chatgpt-catalog" as const },
  { name: "Figma", source: "chatgpt-catalog" as const },
  { name: "Firecrawl", source: "chatgpt-catalog" as const },
  { name: "Fireflies", source: "chatgpt-catalog" as const },
  { name: "getMindmap", source: "chatgpt-catalog" as const },
  { name: "GitHub", source: "chatgpt-catalog" as const },
  { name: "Glossarize", source: "chatgpt-catalog" as const },
  { name: "GoVeda Patent", source: "chatgpt-catalog" as const },
  { name: "Granola", source: "chatgpt-catalog" as const },
  { name: "Health", source: "chatgpt-catalog" as const },
  { name: "HeyGen", source: "chatgpt-catalog" as const },
  { name: "Innovist", source: "chatgpt-catalog" as const },
  { name: "Japanese Speaking Coach", source: "chatgpt-catalog" as const },
  { name: "K-Fortune 사주", source: "chatgpt-catalog" as const },
  { name: "Kahoot!", source: "chatgpt-catalog" as const },
  { name: "Kiuwo", source: "chatgpt-catalog" as const },
  { name: "Language Coach: English", source: "chatgpt-catalog" as const },
  { name: "Learning Commons", source: "chatgpt-catalog" as const },
  { name: "Life Science Research", source: "chatgpt-catalog" as const },
  { name: "Life Sciences NGS Analysis", source: "chatgpt-catalog" as const },
  { name: "Linear", source: "chatgpt-catalog" as const },
  { name: "Lovable", source: "chatgpt-catalog" as const },
  { name: "Magic Tips", source: "chatgpt-catalog" as const },
  { name: "Malwarebytes", source: "chatgpt-catalog" as const },
  { name: "MentorCruise", source: "chatgpt-catalog" as const },
  { name: "Metronome: Music tempo+beat", source: "chatgpt-catalog" as const },
  { name: "Midpage Legal Research", source: "chatgpt-catalog" as const },
  { name: "monday.com", source: "chatgpt-catalog" as const },
  { name: "Music Block", source: "chatgpt-catalog" as const },
  { name: "Notion", source: "chatgpt-catalog" as const },
  { name: "Opera Browser Connector", source: "chatgpt-catalog" as const },
  { name: "Outlook Calendar", source: "chatgpt-catalog" as const },
  { name: "Outlook Email", source: "chatgpt-catalog" as const },
  { name: "PokeBot.ai Career Coach", source: "chatgpt-catalog" as const },
  { name: "Powers Index", source: "chatgpt-catalog" as const },
  { name: "Precise Special Functions", source: "chatgpt-catalog" as const },
  { name: "Premom Ovulation Calculator", source: "chatgpt-catalog" as const },
  { name: "Product Design", source: "chatgpt-catalog" as const },
  { name: "Promova", source: "chatgpt-catalog" as const },
  { name: "Protplex", source: "chatgpt-catalog" as const },
  { name: "Questforge", source: "chatgpt-catalog" as const },
  { name: "QuizFlight", source: "chatgpt-catalog" as const },
  { name: "Quizlet", source: "chatgpt-catalog" as const },
  { name: "Quoted", source: "chatgpt-catalog" as const },
  { name: "Readwise", source: "chatgpt-catalog" as const },
  { name: "Scholar Sidekick", source: "chatgpt-catalog" as const },
  { name: "SciSpace", source: "chatgpt-catalog" as const },
  { name: "Scite", source: "chatgpt-catalog" as const },
  { name: "Self Plagiarism Checker", source: "chatgpt-catalog" as const },
  { name: "Sites", source: "chatgpt-catalog" as const },
  { name: "Slack", source: "chatgpt-catalog" as const },
  { name: "Soul Family AI", source: "chatgpt-catalog" as const },
  { name: "Spotify", source: "chatgpt-catalog" as const },
  { name: "Stripe", source: "chatgpt-catalog" as const },
  { name: "Studyportals", source: "chatgpt-catalog" as const },
  { name: "Supabase", source: "chatgpt-catalog" as const },
  { name: "Superpowers", source: "chatgpt-catalog" as const },
  { name: "Tailo Lens", source: "chatgpt-catalog" as const },
  { name: "Tarot", source: "chatgpt-catalog" as const },
  { name: "Tarteel", source: "chatgpt-catalog" as const },
  { name: "Teams", source: "chatgpt-catalog" as const },
  { name: "TinyFish", source: "chatgpt-catalog" as const },
  { name: "Todoist", source: "chatgpt-catalog" as const },
  { name: "Transkriptor", source: "chatgpt-catalog" as const },
  { name: "TriAstra Astrology & Saju", source: "chatgpt-catalog" as const },
  { name: "Trivana Study — Quiz My Notes", source: "chatgpt-catalog" as const },
  { name: "True Sky", source: "chatgpt-catalog" as const },
  { name: "Udemy", source: "chatgpt-catalog" as const },
  { name: "Vercel", source: "chatgpt-catalog" as const },
  { name: "Vocabulary Trainer Shchebitka", source: "chatgpt-catalog" as const },
  { name: "Wiley Scholar Gateway", source: "chatgpt-catalog" as const },
  { name: "Wolfram", source: "chatgpt-catalog" as const },
  { name: "World Flag Map", source: "chatgpt-catalog" as const },
  { name: "Zotero", source: "chatgpt-catalog" as const },
  { name: "ZZAIM", source: "chatgpt-catalog" as const },
  { name: "エスキスクン", source: "chatgpt-catalog" as const },
  { name: "상식이", source: "chatgpt-catalog" as const },
  { name: "Trello", source: "runtime" as const },
  { name: "Microsoft SharePoint", source: "runtime" as const },
] as const;

export type ChatGPTPluginCatalogEntry = (typeof CHATGPT_PLUGIN_CATALOG)[number];
